### PR TITLE
encode room jids

### PR DESCRIPTION
**Pull request by fippo**
@legastero ^^

not fully happy with this, it seems the JVB can't deal with host/res jids.

### CODE REVIEW

**Comment by legastero** [comment]
Wouldn't this interfere with normal user-user IQ requests?

**Comment by fippo** [comment]
no, those don't have colibri bodies.

**Comment by fippo** [comment]
ah... but it would have eaten user-user errors. I need to investigate the JVB issue at some point... this code makes me sad.

**Comment by fippo** [comment]
no jvb issue, just prosody being weird about hooks.

**Pull request merged**
